"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

def fibonacci():
    i0, i1 = 1, 2
    while True:
        yield i0
        i0, i1 = i1, i0 + i1

def solution():
    N = 4000000
    total = 0
    for f in fibonacci():
        if f > N:
            break
        elif f % 2 == 0:
            total += f
    return total
